# Generated by Django 5.0.6 on 2024-07-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('APH', 'Animal Science'), ('csc', 'computer science'), ('MTS', 'Mathematics')], default='APH', max_length=30),
        ),
    ]
